#!/usr/bin/env perl
use strict;
use warnings;

use Errno qw(EINTR);
use Fcntl qw(F_GETFD F_SETFD LOCK_EX LOCK_NB O_CREAT O_NOFOLLOW O_RDWR SEEK_SET);
use POSIX qw(SIG_BLOCK SIG_SETMASK SIGHUP SIGINT SIGTERM setsid sigprocmask);

sub validate_lock {
    my ($lock, $lock_path) = @_;
    my @opened = stat($lock);
    my @path = lstat($lock_path);
    die "mutation lock must be a private regular file\n"
        unless @opened
        && @path
        && ($opened[2] & 0170000) == 0100000
        && $opened[4] == $<
        && ($opened[2] & 0777) == 0600;
    die "mutation lock must not have hard links\n" unless $opened[3] == 1;
    die "mutation lock path changed while opening\n"
        unless $opened[0] == $path[0] && $opened[1] == $path[1];
}

if (@ARGV && $ARGV[0] eq '--verify') {
    my (undef, $descriptor, $lock_path) = @ARGV;
    die "usage: toolchain-lock --verify DESCRIPTOR LOCK_PATH\n"
        unless defined $descriptor && $descriptor =~ /\A[0-9]+\z/ && defined $lock_path;
    open(my $inherited_lock, "+<&=$descriptor")
        or die "cannot inherit mutation lock descriptor: $!\n";
    validate_lock($inherited_lock, $lock_path);
    flock($inherited_lock, LOCK_EX | LOCK_NB)
        or die "mutation lock descriptor is not held: $!\n";
    exit 0;
}

my ($lock_path, $timeout, @command) = @ARGV;
die "usage: toolchain-lock LOCK_PATH TIMEOUT COMMAND...\n"
    unless defined $lock_path && defined $timeout && @command;
die "invalid lock timeout\n" unless $timeout =~ /\A[1-9][0-9]*\z/;

sysopen(my $lock, $lock_path, O_RDWR | O_CREAT | O_NOFOLLOW, 0600)
    or die "cannot open mutation lock: $!\n";
validate_lock($lock, $lock_path);

local $SIG{ALRM} = sub { die "timed out waiting for the toolchain mutation lock\n" };
alarm $timeout;
flock($lock, LOCK_EX) or die "cannot acquire mutation lock: $!\n";
alarm 0;

my $flags = fcntl($lock, F_GETFD, 0);
defined $flags or die "cannot inspect mutation lock descriptor: $!\n";
fcntl($lock, F_SETFD, 0) or die "cannot preserve mutation lock descriptor: $!\n";

seek($lock, 0, SEEK_SET) or die "cannot seek mutation lock: $!\n";
truncate($lock, 0) or die "cannot truncate mutation lock: $!\n";
print {$lock} "supervisor=$$\n" or die "cannot record mutation lock owner: $!\n";
$ENV{SURGEPILOT_TOOLCHAIN_LOCK_FD} = fileno($lock);

my $child;
my $caught_signal;
my $blocked_signals = POSIX::SigSet->new(SIGHUP, SIGINT, SIGTERM);
my $previous_signals = POSIX::SigSet->new();
defined sigprocmask(SIG_BLOCK, $blocked_signals, $previous_signals)
    or die "cannot block mutation supervisor signals: $!\n";
for my $signal (qw(HUP INT TERM)) {
    $SIG{$signal} = sub {
        $caught_signal = $signal;
        if (defined $child) {
            kill $signal, -$child;
            kill $signal, $child;
        }
    };
}

$child = fork();
defined $child or die "cannot fork mutation command: $!\n";
if ($child == 0) {
    setsid() >= 0 or die "cannot isolate mutation process group: $!\n";
    for my $signal (qw(HUP INT TERM)) {
        $SIG{$signal} = 'DEFAULT';
    }
    defined sigprocmask(SIG_SETMASK, $previous_signals)
        or die "cannot restore mutation command signals: $!\n";
    exec @command;
    die "cannot execute mutation command: $!\n";
}
defined sigprocmask(SIG_SETMASK, $previous_signals)
    or die "cannot restore mutation supervisor signals: $!\n";

while (waitpid($child, 0) == -1) {
    next if $! == EINTR;
    die "cannot wait for mutation command: $!\n";
}
my $status = $?;

if (defined $caught_signal) {
    my %exit_for = (HUP => 129, INT => 130, TERM => 143);
    exit $exit_for{$caught_signal};
}
exit 1 if $status == -1;
exit 128 + ($status & 127) if $status & 127;
exit $status >> 8;
